# Generated by Django 4.2.7 on 2025-03-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_farmer_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmer",
            name="image",
            field=models.ImageField(
                blank=True, default="placeholder.jpg", null=True, upload_to="images"
            ),
        ),
    ]
